### PR TITLE
Add dependencies to dune-project file

### PR DESCRIPTION
**Pull request by Nadrieril**
@giltho like this?

### CODE REVIEW

**Comment by giltho** [comment]
`(menhir :build)` is needed in `name_matcher_parser`'s package definition

**Comment by giltho** [comment]
After installing menhir that seems to be enough :)

**Comment by Nadrieril** [comment]
> `(menhir :build)` is needed in `name_matcher_parser`'s package definition

Done, would you mind one last check?

**Comment by giltho** [comment]
Ah sorry I should have been clearer, `(menhir :build)` is a dependency requirement, it means menhir is needed as a build dependency. So it needs to be in the list of dependencies:

```
(package
  (name name_matcher_parser)
  (synopsis "Parser to define name matchers")
  (description "")
  (depends
    (menhir :build)
    menhirLib
    ppx_deriving
    visitors
    zarith
  )
 )
 ```

**Comment by giltho** [comment]
I'm sorry, I should have just fixed it myself...
opam is weird like this, it's so difficult to get these things right it's annoying.

**Comment by Nadrieril** [comment]
how about now?

**Comment by giltho** [comment]
Opam files need to be regenerated 😭

**Comment by Nadrieril** [comment]
o no x)

**Comment by Nadrieril** [comment]
And now?

**Comment by giltho** [comment]
image
Success!! Thank you!

**Comment by Nadrieril** [comment]
Hooray! THanks for walking me through this :grin:

**Pull request merged**
