### PR TITLE
Retrieve the trait refs of the impl block for inherent methods

### PR DESCRIPTION
**Pull request by Nadrieril**
Uses [my own hax branch](https://github.com/Nadrieril/hax/tree/fix-parent-item-clauses) based on https://github.com/hacspec/hax/tree/charon/globals.

Fixes https://github.com/AeneasVerif/aeneas/issues/97.

### CODE REVIEW

**Comment by Nadrieril** [comment]
This is ready to be merged

**Review by sonmarcho — COMMENTED** [review]
This looks good! I'll let you merge https://github.com/AeneasVerif/charon/pull/102 first, then add/update tests for this PR.

**Comment by Nadrieril** [comment]
Rebased and updated the tests

**Review by sonmarcho — APPROVED** [review]

**Comment by sonmarcho** [comment]
You're free to merge this

**Pull request merged**
